global:
  scrape_interval: 15s       # cada cuánto recoge métricas
  evaluation_interval: 15s   # cada cuánto evalúa reglas de alerta

scrape_configs:
  - job_name: "kds-backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:8000"]
        labels:
          service: "backend"
          env: "development"

  - job_name: "cadvisor"
    metrics_path: "/metrics"
    scrape_interval: 10s          # métricas de contenedores cambian rápido
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          service: "cadvisor"
