apiVersion: 1

datasources:
  - name:   Loki
    uid:    loki                     # UID fijo — referenciado en los dashboards
    type:   loki
    access: proxy
    url:    http://loki:3100         # nombre del servicio en docker-compose
    isDefault: false
    editable: true
    jsonData:
      maxLines:       1000           # máximo de líneas por query en Grafana
      derivedFields:
        # Vincula el campo "logger" con el datasource Loki para navegación rápida
        - name:           logger
          matcherRegex:   ""
          url:            ""
          datasourceUid:  loki
